env:
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  max-len:
    - error
    - code: 100
  require-jsdoc:
    - off

  indent: off
  operator-linebreak: off
